#!/usr/bin/env python2

#
# PyFeyn - a simple Python interface for making Feynman diagrams.
# Copyright (C) 2005-2010 Andy Buckley, Georg von Hippel
#
# PyFeyn is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# PyFeyn is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with PyFeyn; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

from pyfeyn import __version__
from pyfeyn.config import *
from pyfeyn.feynml import *
from optparse import OptionParser
import sys, re


## Parse command line options
_usage = "Usage: %prog [options] hepmlfile"
_version = "%prog " + __version__
_parser = OptionParser(usage=_usage, version=_version)
config.addPyfeynOptions(_parser)
_parser.add_option("--pdf", action="store_true", dest="PDF_OUTPUT",
                   default=True, help="write output in PDF format")
_parser.add_option("--eps", action="store_false", dest="PDF_OUTPUT",
                   default=True, help="write output in EPS format")
_parser.add_option("-o", "--out", dest="OUTPUT_FILE",
                   default=None, help="file to write the output to. An appropriate file extension will be appended if needed")
(_opts, _args) = config.processOptions(_parser)


## Check right number of arguments
if len(_args) != 1:
    sys.stderr.write("Wrong number of arguments... exiting.\n")
    _parser.print_help()
    sys.exit(1)


## Select input and output files
_infile = _args[0]
_outfile = _infile
if _opts.OUTPUT_FILE:
    _outfile = _opts.OUTPUT_FILE


## Get the output file suffix right
_suffix = ".pdf"
if not _opts.PDF_OUTPUT:
    _suffix = ".eps"
if not re.search(r'%s$' % _suffix, _outfile):
    _outfile += _suffix


## Read the file and write out to the chosen filename
reader = FeynMLReader(_infile)
_f = reader.get_diagram(0)
_f.draw(_outfile)
